name: Deploy Serverless

on:
  push:
    branches:
      - main # change if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::771743056881:role/ServerlessPermissions
          aws-region: us-east-1 # or your target region

      - name: Install only layers dependencies
        run: npm install --prefix layers/nodejs # or yarn install

      - name: Deploy with Serverless Framework
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: moodle
          DB_USER: postgres
          DB_PASSWORD: password
          SERVERLESS_ACCESS_KEY: AKYX7jMDdqdhHRuJB8KkKK2rBKITCSO5xTefAHcC5qMWV
          SERVERLESS_LICENSE_KEY: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6IjA5NDlkZDFkLTYxN2EtNGEyMi05MWIwLTI0ZTFiMjMxZmVmMiIsImlhdCI6MTc1NzI2ODQwNiwiZXhwIjoxNzg4ODA0NDA2LCJpc3MiOiJhcHAuc2VydmVybGVzcy5jb20ifQ.QCw3sVeeeMqfwrVnJMoLnnqjO6JwUF9GmhVRh6UBRVXh1yWBomzshNw9ieAOrWAa_4Dok_AhiDGQ54eLVQfQh_Mo8QDkcj2VVdoB_7XlzMWA2dmD9ofT8OGENHoJxax7_Y5utv7QjlOqkfywU8tNt0EtDFxN1CuZVU9iwV7EHoGqAUXLi9znGQgPyCiGmkOoBqCRBYc3oH_8Gbp-1xCmWClLkz3cq81u66tdpMVBABHV5pkF5riWu3cRtDU-bXlwko5jLiV7oL9-vGwUxXPlP2Oz28lwp8iX-48yyi4b9-nhfNYCtQu-341RmIcoIR0GXnmtyaErj5XWYJynTrOGFA
        run: npx serverless deploy
